# Generated by Django 2.0.3 on 2018-04-27 11:00

from django.db import migrations, models
import django.db.models.deletion
import testApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_content_type', models.CharField(choices=[('U', 'Url'), ('T', 'Text')], default='Text', max_length=10)),
                ('input_content', models.TextField(max_length=10000)),
                ('input_datetime', models.DateTimeField(auto_now=True)),
                ('predicted_class', models.CharField(max_length=500)),
                ('confidence_score', models.FloatField()),
                ('prediction_machine_id', models.FloatField()),
                ('prediction_machine_version', models.FloatField()),
                ('prediction_machine_verison_deploy_date', models.DateField()),
            ],
            options={
                'ordering': ('input_class',),
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('topic', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cutoff_25', models.FloatField()),
                ('cutoff_50', models.FloatField()),
                ('cutoff_75', models.FloatField()),
                ('data', models.FileField(storage=testApp.models.OverwriteStorage(), upload_to='uploads')),
            ],
            options={
                'ordering': ('topic',),
            },
        ),
        migrations.AddField(
            model_name='input',
            name='input_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.Topics'),
        ),
    ]
