# Generated by Django 2.0.3 on 2018-04-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='prediction_machine_verison_deploy_date',
            new_name='prediction_machine_deploy_date',
        ),
    ]
