# Generated by Django 2.0.4 on 2018-04-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='input_content',
            field=models.TextField(max_length=10000),
        ),
    ]
