# Generated by Django 2.0.4 on 2018-04-19 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_auto_20180419_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='input_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.Topics'),
        ),
    ]
