# Generated by Django 2.0.3 on 2018-05-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0004_auto_20180518_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='data',
            field=models.FileField(upload_to=''),
        ),
    ]
